apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemq
  template:
    metadata:
      labels:
        app: hivemq
    spec:
      containers:
        - name: hivemq
          image: us.gcr.io/sicove/hivemq:v0.0.2
          ports:
            - containerPort: 1883
          resources:
            requests:
              cpu: 0.3
              memory: 256M
            limits:
              memory: 512M
